# Site settings
title:          "do: pwn()"
description:    "just pwn()"

url:            "https://nonetype.github.io"

# Author
author:
  name:         nonetype
  url:          https://www.facebook.com/nonetype.pwn
  email:        agilemee@gmail.com

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
