# Site settings
title:          "do: pwn()"
description:    "just pwn()"

url:            "https://nonetype.github.io"

# Author
author:
  name:         nonetype
  url:          https://www.facebook.com/nonetype.pwn
  email:        agilemee@gmail.com

remote_theme: chesterhow/tale

permalink: /:year-:month-:day/:title
paginate: 5
sort_field: 'date'
sort_reverse: true

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
